name = "describer"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "describer"

# Secrets (encrypted variables) - set via: wrangler pages secret put ANTHROPIC_API_KEY --project-name=describer
# ANTHROPIC_API_KEY = "set via wrangler CLI as encrypted secret"